### PR TITLE
Added selection support for primitive values

### LINKED ISSUE #13: Config value does not work for drop-down primitives
**Describe the bug**
Configuration values like int or string, that have limited set of options should be displayed as a drop-down box, but are currently just text boxes.

**To Reproduce**
1. Define a primitive config value
2. Decorate with any type of PossibleValues (e.g. PrimitiveValues)
3. Open in configuration 
4. You will not see the expected drop-down 

**Expected behavior**
I would expect a drop-down with the possible values

### PR DESCRIPTION
**Pull request by mmarkwort**
Closes #13 

Tested with `IntegerSteps` & `PrimitiveValues`.

### CODE REVIEW

**Comment by Toxantron** [comment]
Thank you very much. Looks like this was not implemented before and I simply imagined seeing it again.

**Comment by mmarkwort** [comment]
It was already implemented for string lists and enums. I just added the support for integer and floating values.

**Comment by Toxantron** [comment]
That should cover possible values for all primitives now, right?

**Comment by mmarkwort** [comment]
Yes, but we will have an issue with decimals. The conversion will not work if the decimal points are different (Backend en-us and frontend de-de).

**Pull request merged**
