### PR TITLE
Added support for list with primitive types

### LINKED ISSUE #25: Not possible to use a list of strings in configuration
If i want to use a configuration property like

image

then i have the following problem and it is not possible to configure the mentioned list.
The first two entries are expanded in the picture.

image

I expected just to chnage or add some strings.

### PR DESCRIPTION
**Pull request by mmarkwort**
Closes #25 

Problem was, that implementation did only work if the list contains a class. It did not work if the list contains primitives (string, integer, boolean, enum).

I added this feature. There is another problem that is located within `PossibleValuesSerialization.cs` located in the platform. The possible values function returns in this case always `String` as single possible value which is wrong in this case.

So please note, that after adding a new entry you need to save first and then reloading the configuration until the bug in platform is fixed.

### CODE REVIEW

**Comment by Toxantron** [comment]
Thanks for the fix! I fixed the possible value and prototype issue in the platform in PHOENIXCONTACT/MORYX-Platform#76 and verified in the AL with our WPF EntryEditor. Let's wait till the platform is merged and verify here before merging.

**Comment by dbeuchler** [comment]
@mmarkwort I updated the platform with the fixed entry convert. Can you validate that the fixes are working now?

**Comment by dbeuchler** [comment]
> @mmarkwort I updated the platform with the fixed entry convert. Can you validate that the fixes are working now?

I tested your changes but this is my result:

image

**Comment by mmarkwort** [comment]
I need to have a look on this but it seems that a possible value is still being transmitted in the prototype because the drop down should be empty.

**Comment by Toxantron** [comment]
Possible values are included for the collection as a mechanism for the prototype creation and should have a single entry of the type unless its an enum. Possible values for individual members are only set for PossibleValuesAttributes. That was the problem with the previous code.

**Review by dbeuchler — APPROVED** [review]

**Pull request merged**
